development:
  adapter: mysql
  encoding: utf8
  database: kapcha_dev
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: kapcha_test
  username: root
  password: 
  host: localhost